services:
  db:
    image: influxdb:2.1.1-alpine
    restart: on-failure:10
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: root
      DOCKER_INFLUXDB_INIT_BUCKET: public
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: Gr28ZC4m82jgyM
